In [ ]:
# Numpy --> Numerical Python
import numpy as np
print(numpy.__version__)

In [ ]:
arr = np.array([10,20,30,40,50,60])
print(np.sum(arr))

210


In [ ]:
# Python List vs Numpy

# how much execution time will be taken by List and sum()
import time
numbers = list(range(1,100000001))
total = 0
start_time = time.time()  # record start time
for i in numbers:
  total = total + i
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")
#.4f means show 4 digits after the decimal point

Total :  5000000050000000
Execution Time :  13.044517517089844 seconds
Execution Time : 13.0445 seconds


In [ ]:
numbers = np.arange(1,100000001)
total = 0
start_time = time.time()  # record start time
total = np.sum(numbers)
end_time = time.time()  # record end time
print("Total : ",total)
print("Execution Time : ",end_time - start_time,"seconds")
print(f"Execution Time : {end_time - start_time:.4f} seconds")

Total :  5000000050000000
Execution Time :  0.07804155349731445 seconds
Execution Time : 0.0780 seconds


In [ ]:
# array()
# In programming , an array is data structure used to store collection of data values

# Array : Single Dimension (1D) and Multi Dimensional(2D)

# How to create an array(1D)
arr = np.array([10,20,30,40,50,60])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50 60]


In [ ]:
# An array is a collection of Similar Data Type
emp_info = ([123,"Nukki",89.31,True])
print(type(emp_info))
print(emp_info)

<class 'list'>
[123, 'Nukki', 89.31, True]


In [ ]:
# shape property
# used to determine the dimensions of an array
# For 1D array return(n,) --> where n is the number of elements
# For 2D array return(n,m --> where n is the number of rows and m is the number of columns

arr = np.array([10,20,30,40,50,60])
print(arr.shape)

(6,)


In [ ]:
# 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

# Tip for 2D Array
# np.array([])
# 3x3 matrix

# Create a 2x5 Matrix
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# Create a 4x3 Matrix
arr = np.array([[1,2,3],[5,6,7],[8,9,10],[11,12,13]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
# Indexing And Slicing
arr = np.array([10,20,30,40,50,60])
# 10 20 30 40 50 60
# 0  1  2  3  4  5
#-6 -5 -4 -3 -2 -1

print(arr)
print(arr[-1])
print(arr[3])
print(arr[1:5])
print(arr[::-1])

[10 20 30 40 50 60]
60
40
[20 30 40 50]
[60 50 40 30 20 10]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[1,1]) # show me the element which exist at r1 and c1
print(arr[2,2])

# show me the first row only
print(arr[0])

# show me the second column only  FOR COLUMN ONLY USE [:,COLUMN_INDEX_NUMBER]
print(arr[:,1])

print(arr[0:2])

print(arr[:,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
9
[1 2 3]
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]


In [ ]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype)
# stype property helps us to determine the data type of an Array

int64


In [ ]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype)

float64


In [ ]:
arr = np.array([True,False])
print(arr.dtype)

bool


In [ ]:
arr = np.array(["A","B","C"])
print(arr.dtype)

<U1


In [ ]:
arr = np.array(["A","B","C","sjfoosjfajsjfo"])
print(arr.dtype)

<U14


In [ ]:
# we can also use dtype for Conversion
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.nbytes) # total bytes in array

# this int64 means 64 bits
# meaning each and every individual element of an array can take upto 64 bits
# we have 4 elements
# 4 * 64 Bits --> Total Size of Arr : 256 bits
# and if we convert it into bytes 4 element * 8 bytes : 32 bytes


# 6bits 6*4 ==> 24 bits
# Total Size of Arr : 24 bits

int64
32


In [ ]:
arr = np.array([10,20,30,40],dtype="i1")
print(arr.dtype)
print(arr.nbytes)

# this int8 means 8 bits
# meaning each and every individual element of an array can take upto 8 bits
# we have 4 elements
# 4 * 8 Bits --> Total Size of Arr : 32 bits
# and if we convert it into bytes 4 element * 1 bytes : 4 bytes

# when in an array you are storing the age or marks

int8
4


In [ ]:
age = np.array([34,64,63,23,63,85,246,23])
print(age.dtype)
print(age.nbytes)

# i1 --> 8 bytes
# i2 --> 16 bytes
# i3 --> 32 bytes
# i4 --> 64 bytes

int64
64


In [ ]:
a = np.array([10,20,30],dtype="f")
print(a)
print(a.dtype)

[10. 20. 30.]
float32


In [ ]:
a = np.array([10,20,30],dtype="i")
print(a)
print(a.dtype)

[10 20 30]
int32


In [ ]:
# astype() used for conversions
arr = np.array([10. ,20. ,30. ,40., 50.])
arr = arr.astype('i8')
print(arr.dtype)

In [ ]:
# copy() vs view() methods of Numpy

# copy()
# a copy will create a new independent array in a different memory location

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.copy()
print(copied_arr)

# if we make any changes in copied array , it won't effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

In [ ]:
# view()
# a view is the representation of the original array

org_array = np.array([1,2,3,4,5,6])
print(org_array)

copied_arr = org_array.view()
print(copied_arr)

# if we make any changes in copied array , it will effect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_array)

# if we make any changes in org array , it will effect the copied array
org_array[4] = 400
print(org_array)
print(copied_arr)

In [ ]:
org_array = np.array([1,2,3,4,5,6])
copied_arr = org_array.view()

# shares_memory() --> return True if arrays are sharing the same memory location

print(np.shares_memory(org_array,copied_arr))

In [ ]:
# Numpy Array Reshaping
# Converting 1D into 2D or Converting 2D into 1D
# reshape()

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)  # 2x6  3x4  4x3  6x2  12x1  1x12

arr = arr.reshape(3,4)
print(arr)
print(arr.shape)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
print(arr.shape)  # 13x1  1x13
arr = arr.reshape(13,1)
print(arr.shape)
print(arr)

In [ ]:
# numpy.newaxis is used to increase the dimension of the existing array by one more dimension
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# arr[:,np.newaxis]            Column Vector
arr = arr[np.newaxis,:]      # Row Vector
print(arr.shape)

In [ ]:
# Converting 2D into 1D

twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(6)
print(arr)

In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.reshape(-1)
print(arr)

In [ ]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
arr = twod.flatten()
print(arr)

In [ ]:
# concatenate()
# used to join 2 arrays

pp1 = np.array([20,60,80,45,32])
pp2 = np.array([10,20,30,40,50,67,32,90])
pp3 = np.array([100,200,300,400])
arr = np.concatenate((pp1,pp2,pp3))
print(arr)

In [ ]:
t1 = np.array([[1,2],[3,4]])
t2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((t1,t2))
print(arr)

In [ ]:
# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
arr = np.array_split(arr,3)
print(arr[0])
print(arr[1])
print(arr[2])

In [ ]:
# Sorting
# np.sort() by default it will sort in an ascending order

prices = np.array([74,64,73,97,24,73,85,27,842,277,38,27,84])
print(np.sort(prices))

[ 24  27  27  38  64  73  73  74  84  85  97 277 842]


In [ ]:
prices = np.array([74,64,73,97,24,73,85,27,842,277,38,27,84])
print(np.sort(prices)[::-1]) # descending order

[842 277  97  85  84  74  73  73  64  38  27  27  24]


In [ ]:
# Filter and Searching In An Array
prices = np.array([74,64,73,97,24,73,85,27,842,277,38,27,84])
print(prices)

for i in prices:
  if i>=50:
    print(i)

[ 74  64  73  97  24  73  85  27 842 277  38  27  84]
74
64
73
97
73
85
842
277
84


In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
# Boolean Masking
prices>=50


array([ True,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True])

In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
# Boolean Masking
newarr = prices[prices>=50] # here we are applying a filter prices[showMeOnlyTrueValues]
print(newarr)

In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
EvenArr = prices[prices%2==0]
print(EvenArr)

[ 74  64  14  24 842  38  84]


In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
# np.where(expression)
# np.where returns INDEX NUMBERS
res = np.where(prices%2==0)
print(prices[res])

[ 74  64  14  24 842  38  84]


In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
res = np.where((prices%2==0) & (prices>=50))
print(prices[res])

# & combines both conditions

[ 74  64 842  84]


In [ ]:
prices = np.array([74,64,14,73,97,24,73,85,27,842,277,38,27,84])
print(prices[(prices%2==0) & (prices>=50)])


[ 74  64 842  84]


In [ ]:
# SALARY CLASSIFICATION
salary = np.array([25000,40000,55000,70000,30000,90000])
# Replace salary witth High if salary >= 60000
# Replace salary with Medium if salary >= 40000 and <= 60000
# Otherwise Low

# np.where(condition,value_if_true,value_if_false)

res = np.where(salary>=60000,"High",np.where(salary>=40000,"Medium","Low"))
print(res)

['Low' 'Medium' 'Medium' 'High' 'Low' 'High']


In [ ]:
# Numpy Random Module
from numpy import random
x = random.randint(100) # 1 till 100
print(x)

14


In [ ]:
x = random.randint(100,150) # 100 till 150
print(x)

In [ ]:
# rand() generate random float
# method returns a random float value between 0 and 1

print(random.rand())

0.8597653074098546


In [ ]:
# generating ID Array
arr =random.randint(30,120,size=(3,4)) # size means dimensions of  an array
print(arr)

[[34 53 91 53]
 [60 90 90 89]
 [53 74 42 48]]


In [ ]:
arr = random.rand(10)
print(arr)

[0.28703314 0.72241617 0.19753713 0.52013076 0.64029438 0.69786305
 0.44387588 0.0620974  0.44368677 0.56891026]


In [ ]:
arr = random.rand(5,4)
print(arr)

[[0.00610276 0.93542663 0.43605365 0.21259828]
 [0.6118567  0.57399376 0.35066577 0.16281833]
 [0.99347893 0.47097844 0.71032024 0.28521869]
 [0.97963265 0.34924796 0.69153416 0.30170942]
 [0.23371068 0.77849203 0.1426931  0.08754446]]


In [ ]:
# choice() method allows you to generate a random value
# based on an array of values

arr = random.choice([10,20,30,40,50,60])
print(arr)

10


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(7))
print(arr)

[50 30 10 60 20 50 10]


In [ ]:
arr = random.choice([10,20,30,40,50,60],size=(5,4))
print(arr)

[[50 50 20 10]
 [10 10 20 30]
 [60 30 30 10]
 [40 10 50 60]
 [40 50 60 10]]


In [ ]:
# numpy.zeros()
# this function allows us to create an array filled with zeros
# default data type will be float

x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x = np.zeros((3,3),dtype="i")
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#numpy.ones()
# this function allows us to crate an array filled with ones
# default data type will be float

x = np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x = np.ones((3,3),dtype="i")
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# numpy.sum()
# used to compute the sum of all elements

x = np.random.randint(50,size=(120))
print(x)

[12 42  7  7 13 38 43 23  2 46 28 38 31 36 13 49 12 14 11 29 10 13  7 39
 21 14 16  9 25 46  4 10 30 36  2  0 17 16 37 10 43 22 34 13 23 37 21 39
  3  2 12 46 31 36  2 31 49 17 12 29 16 16 43 32  9 32 30  3 20 20 39 45
 45  4 43  1 20  8 21 43 28  6 49 33 39 11 21 26 13 36 13  6  9  8 32  9
 25  9 45 37 18 35 28 33 21 27 48 41 36  9  4  6  6 33  2  9 30 19 36  0]


In [ ]:
print("Sum Of An Array")
print(np.sum(x))

Sum Of An Array
2744


In [ ]:
# numpy.mean()
# mean value is the average value
print("Mean Of An Array")
print(np.mean(x))

Mean Of An Array
22.866666666666667


In [ ]:
print("Min of An Array")
print(np.min(x))
print("Max of An Array")
print(np.max(x))

Min of An Array
0
Max of An Array
49


In [ ]:
# numpy.unique()
# return unique elements as a sorted array
a = np.array([1,2,3,45,235,6,7,8,9,0,9,34,73,8,27,8,3,78,8,8,3,7])
print(np.unique(a))

[  0   1   2   3   6   7   8   9  27  34  45  73  78 235]


In [ ]:
a = np.array([1,2,3,45,235,6,7,8,9,0,9,34,73,8,27,8,3,78,8,8,3,7])
uv , i = np.unique(a,return_index=True)
print(uv)
print(i)
# return_index --> it will print the index numbers

[  0   1   2   3   6   7   8   9  27  34  45  73  78 235]
[ 9  0  1  2  5  6  7  8 14 11  3 12 17  4]


In [ ]:
#argsort --> reorder the index numbers in a proper sequence
f = uv[np.argsort(i)]

[  1   2   3  45 235   6   7   8   9   0  34  73  27  78]


In [ ]:
a = np.array([1,2,3,45,235,6,7,8,9,0,9,34,73,8,27,8,3,78,8,8,3,7])
uv , i = np.unique(a,return_index=True)
uv[np.argsort(i)]

array([  1,   2,   3,  45, 235,   6,   7,   8,   9,   0,  34,  73,  27,
        78])

In [ ]:
# arange()
print(np.arange(10))
print(np.arange(10,20))
print(np.arange(10,20,2))

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [ ]:
# Numpy Broadcasting
arr1 = np.array([16,43,65,43])
arr2 = np.array([13,22,28])
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
# in which cases there will be no broadcasting error
# case 1 : when arrays are equal
# casse 2 : if anyone of them is 1

arr1 = np.array([12,42,52])
arr2 = np.array([2])
print(arr1+arr2)

[14 44 54]
